public class bankaccount {
    public string nameofaccountholder;
    public string aadharnumber;
    public string pannumber;
    public string mobilenumber;
     
    public void basicdetailsofaccountholder(){
        
        system.debug('name of account holder'+this.nameofaccountholder);
        
        system.debug('aadharnumber'+this.nameofaccountholder);
        
        system.debug('pannumber'+this.nameofaccountholder);
        
        system.debug('mobilenumber'+this.nameofaccountholder);
    }
    
   
    }